Main() {
    Result = 0

    Result = Result - 5*a
    repeat 5 {
        Result = Result + a
    }

    repeat 0 {
        Result = Result + b
    }

    repeat -10 {
        Result = Result + c
    }

    Result = Result - 10*d
    repeat 2 {
        repeat 5 {
            Result = Result + d
        }
    }

    Result = Result - 9*e
    repeat 5 {
        if Result == -5*e {
            Result = Result + 5*e
        } else {
            Result = Result + e
        }
    }

    return Result
}