Main() {
    Result = 0

    if !(Expand((x + 1)^(-3/2)) == (x^3 + 3*x + 3*x^2 + 1)^(-1/2)) { Result = Result + a }

    if !(Expand((3*(x + 1))^((x + 1)*x)) == (3*x + 3)^(x^2 + x)) { Result = Result + b }

    if !(Expand(x * (y + 2) * (z + 3)) == x*y*z + 3*x*y + 2*x*z + 6*x) { Result = Result + c }

    if !(Expand((2*a + 3*b)*(a + 2*b)*(a - b)) == 2*a^3 + 5*b*a^2 - a*b^2 - 6*b^3) { Result = Result + d }
    
    if !(Expand((x^2 + 2*x + 3) * (x - 1)^2) == x^4 -4*x + 3) { Result = Result + e }

    return Result
}