Main() {
    Result = 0

    if !(SimpleDerive(x^2 + 3*x + x + y + 5, x) == 2*x + 4) { Result = Result + a }

    if !(SimpleDerive(x^2 + 3*x + x + y + 5, y) == 1) { Result = Result + b }

    if !(SimpleDerive(3*x*y + y^2, y) == 3*x + 2*y) { Result = Result + c }

    if !(SimpleDerive((x^2 + 3)/(x^4 -4), x) == -(4*(3+x^2)*x^3)/(-4+x^4)^2 + (2*x)/(-4+x^4)) { Result = Result + d }

    if !(SimpleDerive((x^-1) + (x^-2), x) == -2/x^3-1/x^2) { Result = Result + e }

    return Result
}